#!/usr/bin/python3
#
# Part of RedELK
#
# Author: Lorenzo Bernardi / @fastlorenzo
#
from modules.helpers import *
import traceback
import config

info = {
    'version': 0.1,
    'name': 'dummy_alarm module',
    'alarmmsg': 'ALARM GENERATED BY DUMMY',
    'description': 'This alarm always triggers. Only use for testing purposes',
    'type': 'redelk_alarm',
    'submodule': 'alarm_dummy'
}

class Module():
    def __init__(self):
        #print("class init")
        pass
    
    def run(self):
        ret = {}
        alarmLines = []
        ret['info'] = info
        ret['hits'] = {}
        ret['hits']['hits'] = []
        ret['results'] = {}
        ret['hits']['total'] = 0
        if config.DEBUG > 0:
            print("[a] module %s . generating results. config.DEBUG set to %s"%(ret['info']['name'],config.DEBUG))
            for num in range(3):
                ret['results'][num] = {
                    'test': {
                        'key': 'val_%s'%num
                        }
                    }
                ret['hits']['total'] = ret['hits']['total'] +1
        #ret['hits']['total'] = len(ret['hits']['hits'])

        print("[a] finished running module %s . result: %s hits"%(ret['info']['name'],ret['hits']['total']))
        #print(ret)
        return(ret)
