---
redelk_local_repo_path: "{{ playbook_dir | dirname }}"
redelk_openssl_config_path: certs/config.cnf
redelk_package_ssh_dir: "{{ redelk_local_repo_path }}/sshkey"
redelk_package_archives:
  - name: elkserver
    path: "{{ redelk_local_repo_path }}/elkserver"
    dest: "{{ redelk_local_repo_path }}/elkserver.tgz"
  - name: c2servers
    path: "{{ redelk_local_repo_path }}/c2servers"
    dest: "{{ redelk_local_repo_path }}/c2servers.tgz"
  - name: redirs
    path: "{{ redelk_local_repo_path }}/redirs"
    dest: "{{ redelk_local_repo_path }}/redirs.tgz"
