#
# Part of RedELK
# Docker compose config for RedELK development
#
# Authors:
# - Outflank B.V. / Marc Smeets
# - Lorenzo Bernardi (@fastlorenzo)
#

version: "3.3"

networks:
  net:
    driver: bridge

volumes:
  es_data:
    driver: local
  kibana_data:
    driver: local
  bloodhound_data:
    driver: local

services:
  elasticsearch:
    container_name: redelk-elasticsearch
    build: ./docker/redelk-elasticsearch
    networks:
      - net
    # Only for dev purposes, expose ES port to everywhere
    ports:
      - "9200:9200"
    expose:
      - "9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - ./mounts/certs:${CERTS_DIR_ES}
      - ./mounts/elasticsearch-config/jvm.options.d:/usr/share/elasticsearch/config/jvm.options.d
    environment:
      - discovery.type=single-node
      - cluster.name=redelk-cluster
      - node.name=redelk-node1
      - bootstrap.memory_lock=true
      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=${CERTS_DIR_ES}/redelk-elasticsearch/redelk-elasticsearch.key
      - xpack.security.http.ssl.certificate_authorities=${CERTS_DIR_ES}/ca/ca.crt
      - xpack.security.http.ssl.certificate=${CERTS_DIR_ES}/redelk-elasticsearch/redelk-elasticsearch.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.certificate_authorities=${CERTS_DIR_ES}/ca/ca.crt
      - xpack.security.transport.ssl.certificate=${CERTS_DIR_ES}/redelk-elasticsearch/redelk-elasticsearch.crt
      - xpack.security.transport.ssl.key=${CERTS_DIR_ES}/redelk-elasticsearch/redelk-elasticsearch.key
      - xpack.security.authc.realms.native.redelk.order=1
      - COMPOSE_PROJECT_NAME=redelk
      - CERTS_DIR_ES=${CERTS_DIR_ES}
      - CERTS_DIR_KBN=${CERTS_DIR_KBN}
      - CERTS_DIR_LOGSTASH=${CERTS_DIR_LOGSTASH}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - CREDS_kibana_system=${CREDS_kibana_system}
      - CREDS_logstash_system=${CREDS_logstash_system}
      - CREDS_redelk_ingest=${CREDS_redelk_ingest}
      - CREDS_redelk=${CREDS_redelk}
      - ES_URL=${ES_URL}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE}"
        max-file: "${LOG_MAX_FILE}"

  logstash:
    container_name: redelk-logstash
    build: ./docker/redelk-logstash
    networks:
      - net
    ports:
      - "5044:5044"
    expose:
      - "9600"
    volumes:
      # Logstash uses 2 sets of TLS certs:
      #  1) the CA and certs generated by the initial-setup.sh script, which is used for outside comm with redirs and C2servers: CERTS_DIR_REDELK
      - ./mounts/logstash-config/certs_inputs:${CERTS_DIR_REDELK}
      #  2) the certs generated by ES for internal comm between ELK components: CERTS_DIR_LOGSTASH
      - ./mounts/certs:${CERTS_DIR_LOGSTASH}
      - ./mounts/redelk-logs:/var/log/redelk
      # The logstash filter rules are mounted to the filesystem. You can edit them yourself, e.g. add filters for your own C2
      - ./mounts/logstash-config/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./mounts/logstash-config/redelk-main:/usr/share/logstash/redelk-main
    environment:
      - node.name=redelk-logstash
      - config.reload.automatic:true
      - CERTS_DIR_REDELK=${CERTS_DIR_REDELK}
      - CERTS_DIR_LOGSTASH=${CERTS_DIR_LOGSTASH}
      - CERTS_LOGSTASH_OUTPUT_CA=${CERTS_LOGSTASH_OUTPUT_CA}
      - CERTS_LOGSTASH_INPUT_KEY=${CERTS_LOGSTASH_INPUT_KEY}
      - CERTS_LOGSTASH_INPUT_CRT=${CERTS_LOGSTASH_INPUT_CRT}
      - CREDS_redelk_ingest=${CREDS_redelk_ingest}
      - XPACK_MONITORING_ENABLED=false
      - XPACK_MONITORING_ELASTICSEARCH_HOSTS=["${ES_URL}"]
      - XPACK_MONITORING_ELASTICSEARCH_USERNAME=logstash_system
      - XPACK_MONITORING_ELASTICSEARCH_PASSWORD=${CREDS_logstash_system}
      - XPACK_MONITORING_ELASTICSEARCH_SSL_CERTIFICATE_AUTHORITY=${CERTS_LOGSTASH_OUTPUT_CA}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE}"
        max-file: "${LOG_MAX_FILE}"
    depends_on:
      - elasticsearch

  kibana:
    container_name: redelk-kibana
    build: ./docker/redelk-kibana
    networks:
      - net
    # Only for dev purposes, expose kibana port
    ports:
      - "5601:5601"
    expose:
      - "5601"
    volumes:
      - kibana_data:/usr/share/kibana/data
      - ./mounts/certs:${CERTS_DIR_KBN}
    environment:
      - ELASTICSEARCH_HOSTS=${ES_URL}
      - XPACK_SECURITY_ENABLED=true
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${CREDS_kibana_system}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=${CERTS_DIR_KBN}/ca/ca.crt
      - SERVER_SSL_CERTIFICATEAUTHORITIES=${CERTS_DIR_KBN}/ca/ca.crt
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_CERTIFICATE=${CERTS_DIR_KBN}/redelk-kibana/redelk-kibana.crt
      - SERVER_SSL_KEY=${CERTS_DIR_KBN}/redelk-kibana/redelk-kibana.key
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${KBN_XPACK_ENCRYPTEDSAVEDOBJECTS}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE}"
        max-file: "${LOG_MAX_FILE}"
    depends_on:
      - logstash

  nginx:
    container_name: redelk-nginx
    image: nginx:latest
    networks:
      - net
    volumes:
      - ./mounts/nginx-config:/etc/nginx/templates
      - ./mounts/redelk-www:/var/www/html
      - ${CERTS_DIR_NGINX_LOCAL}:${CERTS_DIR_NGINX}
      - ${CERTS_DIR_NGINX_CA_LOCAL}:${CERTS_DIR_NGINX_CA}
      - ./mounts/certbot/conf:/etc/letsencrypt
      - ./mounts/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TLS_NGINX_CRT_PATH=${TLS_NGINX_CRT_PATH}
      - TLS_NGINX_KEY_PATH=${TLS_NGINX_KEY_PATH}
      - TLS_NGINX_CA_PATH=${TLS_NGINX_CA_PATH}
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & /docker-entrypoint.d/20-envsubst-on-templates.sh; nginx -g \"daemon off;\"'"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE}"
        max-file: "${LOG_MAX_FILE}"
    depends_on:
      - jupyter
      - kibana
      - bloodhound

  certbot:
    container_name: redelk-certbot
    image: certbot/certbot
    networks:
      - net
    volumes:
      - ./mounts/certbot/conf:/etc/letsencrypt
      - ./mounts/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE}"
        max-file: "${LOG_MAX_FILE}"
    depends_on:
      - nginx

  base:
    container_name: redelk-base
    build: ./docker/redelk-base
    networks:
      - net
    volumes:
      - ./mounts/redelk-config/etc/cron.d:/etc/cron.d
      - ./mounts/redelk-config/etc/redelk:/etc/redelk
      - ./mounts/redelk-logs:/var/log/redelk
      - ./mounts/redelk-ssh:/home/redelk/.ssh
      - ./mounts/redelk-www/c2logs:/var/www/html/c2logs
      - ./docker/redelk-base/redelkinstalldata/scripts:/usr/share/redelk/bin
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE}"
        max-file: "${LOG_MAX_FILE}"
    depends_on:
      - nginx

  jupyter:
    container_name: redelk-jupyter
    build: ./docker/redelk-jupyter
    networks:
      - net
    expose:
      - "8888"
    volumes:
      - ./mounts/jupyter-workbooks:/home/jovyan/work
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE}"
        max-file: "${LOG_MAX_FILE}"

  bloodhound:
    container_name: redelk-bloodhound
    image: neo4j:4.2.13
    networks:
      - net
    volumes:
      - bloodhound_data:/data
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH}
      - NEO4J_dbms_memory_heap_initial__size=${NEO4J_dbms_memory_heap_initial__size}
      - NEO4J_dbms_memory_heap_max__size=${NEO4J_dbms_memory_heap_max__size}
      - NEO4J_dbms_memory_pagecache_size=${NEO4J_dbms_memory_pagecache_size}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE}"
        max-file: "${LOG_MAX_FILE}"
    depends_on:
      - jupyter

  filebeat:
    container_name: redelk-sample-data
    image: docker.elastic.co/beats/filebeat:7.16.3
    networks:
      - net
    volumes:
      - ./mounts/sample-data/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./mounts/sample-data/logs:/var/log/sample-data:ro
      - ./mounts/certs:/usr/share/filebeat/certs:ro
    command: ['filebeat', '-e', '-strict.perms=false']
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE}"
        max-file: "${LOG_MAX_FILE}"
    depends_on:
      - logstash
