---
- hosts: elkservers:c2servers:redirs
  gather_facts: false
  tags:
    - pre
  pre_tasks:
    - name: Check known_hosts for selected hosts
      ansible.builtin.command:
        argv:
          - ssh-keygen
          - -F
          - "{{ ansible_host }}"
      delegate_to: localhost
      register: has_entry_in_known_hosts_file
      changed_when: false
      failed_when: false

    - name: Ignore host key on first run
      when: has_entry_in_known_hosts_file.rc == 1
      ansible.builtin.set_fact:
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

    - name: Delayed gathering of facts
      ansible.builtin.setup:

  roles:
    - name: redelk-package-prep
      when: redelk_generate_packages | bool
      tags: pre

- hosts: elkservers
  roles:
    - name: docker
      tags: redelk-server
    - name: redelk-server
      tags: redelk-server

- hosts: c2servers
  roles:
    - name: redelk-client
      when: deploy_redelk == true
      tags: redelk-client

- hosts: redirs
  roles:
    - name: redelk-client
      when: deploy_redelk == true
      tags: redelk-client
