name: Build and push containers

on:
  push:
    # For push to branches (e.g. master, features branches, etc.)
    branches:
      - "*"
    paths:
      - "elkserver/docker/**"
      - ".github/workflows/containers-build-push.yml"
    # For releases
    tags:
      - "*"
  # For pull requests
  pull_request:
    branches:
      - "*"
    paths:
      - "elkserver/docker/**"
      - ".github/workflows/containers-build-push.yml"

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - base
          - elasticsearch
          - jupyter
          - kibana
          - logstash
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare
        id: prepare
        run: |
          if [[ "x$DOCKER_REPO" == "x" ]]; then
            DOCKER_REPO=outflanknl
          fi
          DOCKER_IMAGE="${DOCKER_REPO}/redelk-${{ matrix.container }}"
          echo ::set-output name=docker_image::${DOCKER_IMAGE}
          echo ::set-output name=docker_repo::${DOCKER_REPO}
          echo ::set-output name=build_args::BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            VCS_REF=${GITHUB_SHA::8}
        env:
          DOCKER_REPO: ${{ secrets.DOCKER_REPO }}

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v4
        with:
          images: |
            ${{ steps.prepare.outputs.docker_image }}
            ${{ github.repository_owner }}/redelk-${{ matrix.container }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        # if: ${{ github.event_name != 'pull_request' }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.container }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.container }}-

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: elkserver/docker/redelk-${{ matrix.container }}
          file: ./elkserver/docker/redelk-${{ matrix.container }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: ${{ steps.prepare.outputs.build_args }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          # tags: |
          #   ${{ steps.semver_parser.outputs.major }}
          #   ${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}
          #   ${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}.${{ steps.semver_parser.outputs.patch }}

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
