name: Lint - Python

on:
  push:
    paths:
      - "elkserver/docker/redelk-base/redelkinstalldata/scripts/**"
      - .github/workflows/lint-python.yml
  pull_request:
    paths:
      - "elkserver/docker/redelk-base/redelkinstalldata/scripts/**"
      - .github/workflows/lint-python.yml

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.6
        uses: actions/setup-python@v4
        with:
          python-version: "3.6.9"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pylint Pillow
          pip install -r elkserver/docker/redelk-base/redelkinstalldata/scripts/requirements.txt

      - name: Analysing the code with black
        run: |
          black --check --diff --color elkserver/docker/redelk-base/redelkinstalldata/scripts

      - name: Analysing the code with pylint
        run: |
          find elkserver/docker/redelk-base/redelkinstalldata/scripts -not -path '*/Chameleon/*' -name '*.py' -print0 | xargs -0 -i sh -c 'echo pylint {}; PYLINTRC=$(pwd)/elkserver/docker/redelk-base/redelkinstalldata/scripts/.pylintrc pylint {}'
