name: Lint - Python

on:
  push:
    paths:
      - "elkserver/docker/redelk-base/redelkinstalldata/scripts/**"
      - .github/workflows/lint.yml
  pull_request:
    paths:
      - "elkserver/docker/redelk-base/redelkinstalldata/scripts/**"
      - .github/workflows/lint.yml

jobs:
  lint:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Check files using black formatter
        uses: datadog/action-py-black-formatter@v2.5
        with:
          check_mode: true
          additional_args: "-t py36 elkserver/docker/redelk-base/redelkinstalldata/scripts"
