#
# Part of RedELK
# Dockerfile for RedELK Logstash image
#
# Authors:
# - Outflank B.V. / Marc Smeets
# - Lorenzo Bernardi
#

FROM docker.elastic.co/logstash/logstash:7.17.9
LABEL maintainer="Outflank B.V. / Marc Smeets"
LABEL description="RedELK Logstash"

# Create relevant directories
#RUN mkdir -p /usr/share/logstash/redelk-main/conf.d
#RUN mkdir -p /usr/share/logstash/redelk-main/certs

# Move files to proper locations
#COPY --chown=logstash:logstash ./redelkinstalldata/config/pipelines.yml /usr/share/logstash/config/pipelines.yml
#COPY --chown=logstash:logstash ./redelkinstalldata/redelk-main/conf.d/. /usr/share/logstash/redelk-main/conf.d/
#COPY --chown=logstash:logstash ./redelkinstalldata/redelk-main/scripts/. /usr/share/logstash/redelk-main/scripts/
